[theme]

# Primary accent for interactive elements
primaryColor = '#B73D15' #orange

# Background color for the main content area
backgroundColor = '#FFB96B'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = 'EEA58D'

# Color used for almost all text
textColor = '#FFFFFF'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace)
# Default: "sans serif"
font = "sans serif"